function [scenario, testName, roadWidth]= oblongTest()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.10 (R2021a) and Automated Driving Toolbox 3.3 (R2021a).
% Generated on: 29-Jul-2021 19:05:36
testName = 'Oblong Test';

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [32.7 20.5 0;
    32.5 -5.8 0;
    32.7 -29.3 0;
    15.6 -29.7 0;
    1.3 -29.8 0;
    2.7 -7.1 0;
    3.5 20.7 0;
    18.4 21.3 0;
    32.7 20.5 0];
roadWidth = 3;
road(scenario, roadCenters, roadWidth, 'Name', 'Road');

